# Docker doesn't include buildfile inheritance yet - rubbish. No DRY Dockerfile's for us :-(
# Do not install dev dependencies
FROM dangerfarms/geodrf-alpine:latest
RUN mkdir /app
WORKDIR /app
ADD requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
ADD . /app/
