# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 14:23
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20160720_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='host_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=[], size=None),
        ),
    ]
