# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 14:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import formhero.providers.dbform
import formhero.providers.email


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('handler', models.TextField(choices=[('db', formhero.providers.dbform.Backend), ('email', formhero.providers.email.Backend)])),
                ('config', django.contrib.postgres.fields.jsonb.JSONField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.App')),
            ],
        ),
    ]
