# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 16:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
    ]
