# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 14:50
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_form_allowed_hosts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='allowed_hosts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
        ),
    ]
